Fix Firebase class print
JohnCoene/firebase pull request #27
Opened 2022-03-23 07:58 UTC by itkonen

2022-03-23 09:09 UTC, itkonen commented
I'm not quite sure if the test for a user being signed in is valid in all states (e.g. after sign-out or connection error).

2022-03-23 11:53 UTC, JohnCoene requested changes

2022-03-23 11:53 UTC, JohnCoene commented on R/class-auth.R
> +          emailVerified = user$response$emailVerified,
This class is used as parent for all other auth methods.
Some of these fields in the `user` object may not be available, e.g. `emailVerified`.
If we want clearer `print` methods we can override in children classes.

2022-03-23 11:54 UTC, JohnCoene commented
I did not work on the `print` methods too much because being shiny-dependent it tends not to be printed

2022-03-26 09:32 UTC, itkonen commented
I included a `Filter` function in f0db083339c013fc56f7137f285b8312ab1557ed to clean up fields which might be missing. I guess this should also work for the children classes. Also, it would easy to add other fields that the children classes might have.

2022-03-26 10:05 UTC, JohnCoene commented
Thank you, that works!

2022-03-26 10:05 UTC, merged